syntax = "proto3";

package holistik.common.types.v1;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/loicsikidi/holistik/proto/gen/proto/go/holistik/api/common/types/v1;typesv1";

enum KeyStatus {
  // KEY_STATUS_UNSPECIFIED represents an unspecified key status.
  KEY_STATUS_UNSPECIFIED = 0;
  // KEY_STATUS_ACTIVE represents an active key.
  KEY_STATUS_ENABLED = 1;
  // KEY_STATUS_DISABLED represents a disabled key.
  KEY_STATUS_DISABLED = 2;
  // KEY_STATUS_DESTROYED represents a destroyed key.
  KEY_STATUS_DESTROYED = 3;
}

message X509KeyPairs {
  repeated X509KeyPair pairs = 1;
}

// X509KeyPair is a key pair used to sign X.509 certificates.
message X509KeyPair {
  // KeyID is the identifier of the key.
  // This identifier is stored alongside the key in the keyset.
  bytes keyid = 1;

  // Status is the status of the key.
  KeyStatus status = 2;

  // Cert is a PEM encoded TLS cert
  bytes cert = 3;

  // CRL is a DER-encoded revocation list.
  bytes crl = 4;
}

message JWTKeyPairs {
  repeated JWTKeyPair pairs = 1;
}

// JWTKeyPair is a key pair used to sign JWT.
message JWTKeyPair {
  // PublicKey is a PEM encoded public key.
  bytes public_key = 1;

  // KeyID is the identifier of the key.
  // This identifier is stored alongside the key in the keyset.
  bytes keyid = 2;

  // Status is the status of the key.
  KeyStatus status = 3;
}

// CAKeySet is the set of CA keys.
message CAKeySet {
  enum KeySetType {
    KEYSET_TYPE_UNSPECIFIED = 0;
    KEYSET_TYPE_INSECURE = 1;
    KEYSET_TYPE_ENCRYPTED = 2;
  }

  enum KeySetBackend {
    KEYSET_BACKEND_UNSPECIFIED = 0;
    KEYSET_BACKEND_RAW = 1;
    //    // TPM is a private key backed by a TPM device.
    //    KEYSET_BACKEND_TPM = 2;
    //   // PKCS11 is a private key backed by a PKCS11 device such as HSM.
    //   KEYSET_BACKEND_PKCS11 = 3;
    //   // GCP_KMS is a private key backed by GCP KMS.
    //   KEYSET_BACKEND_GCP_KMS = 4;
    //   // AWS_KMS is a private key backed by AWS KMS.
    //   KEYSET_BACKEND_AWS_KMS = 5;
  }

  // Type is the type of the keyset.
  KeySetType type = 1;

  // keyset_data is a serialized Tink keyset.
  // google.crypto.tink.Keyset or google.crypto.tink.EncryptedKeyset
  bytes keyset_data = 2;

  // Backend is the backend the keyset needs to interact with.
  //
  // Note: if keyset_type is INSECURE, this field must be equal to RAW.
  KeySetBackend keyset_backend = 3;

  // UseEnvelopeEncryption indicates whether envelope encryption needs to be used.
  bool use_envelope_encryption = 4;

  // KeyPairs contains the key pairs linked to the keyset.
  oneof key_pairs {
    X509KeyPairs x509 = 5;
    JWTKeyPairs jwt = 6;
  }
}

// PIVSlotKey is the key reference for a specific PIV slot.
enum PIVSlotKey {
  // PIV slot key not specified.
  PIV_SLOT_KEY_UNSPECIFIED = 0;
  // PIV slot key 9a. This is the default slot for pin_policy=never, touch_policy=never.
  PIV_SLOT_KEY_9A = 1;
  // PIV slot key 9c. This is the default slot for pin_policy=never, touch_policy=cached.
  PIV_SLOT_KEY_9C = 2;
  // PIV slot key 9d. This is the default slot for pin_policy=once, touch_policy=cached.
  PIV_SLOT_KEY_9D = 3;
  // PIV slot key 9e. This is the default slot for pin_policy=once, touch_policy=never.
  PIV_SLOT_KEY_9E = 4;
}

// SignatureAlgorithmSuite represents the suite of cryptographic signature algorithms used in the cluster.
enum SignatureAlgorithmSuite {
  // SIGNATURE_ALGORITHM_SUITE_UNSPECIFIED represents an unspecified signature algorithm suite.
  SIGNATURE_ALGORITHM_SUITE_UNSPECIFIED = 0;
  // SIGNATURE_ALGORITHM_SUITE_BALANCED_V1 aims to strikes a balance between
  // security, compatibility, and performance. It uses Ed25519 for most SSH
  // keys, ECDSA on the NIST P256 curve for most TLS keys, and 2048-bit RSA
  // where necessary for compatibility with third-party software.
  SIGNATURE_ALGORITHM_SUITE_BALANCED_V1 = 1;
  // SIGNATURE_ALGORITHM_SUITE_FIPS_V1 is tailored for FIPS compliance. It is
  // based on the BALANCED_V1 suite but replaces all instances of Ed25519 with
  // ECDSA on the NIST P256 curve.
  SIGNATURE_ALGORITHM_SUITE_FIPS_V1 = 2;
  // SIGNATURE_ALGORITHM_SUITE_HSM_V1 is tailored for clusters using an HSM or
  // KMS service to back CA private material. It is based on the BALANCED suite
  // but replaces Ed25519 with ECDSA on the NIST P256 curve for CA keys only,
  // not for server or client keys. It is also valid to use the LEGACY for FIPS
  // suites if your cluster uses an HSM or KMS.
  SIGNATURE_ALGORITHM_SUITE_HSM_V1 = 3;
}
