syntax = "proto3";

package holistik.api.certauthority.v1;

import "holistik/common/header/v1/metadata.proto";
import "holistik/common/types/v1/types.proto";

option go_package = "github.com/loicsikidi/holistik/proto/gen/proto/go/holistik/api/certauthority/v1;certauthorityv1";

// CertAuthority represents a CA
message CertAuthority {
  // The kind of resource represented.
  string kind = 1;
  // Differentiates variations of the same kind. All resources should
  // contain one, even if it is never populated.
  string sub_kind = 2;
  // The version of the resource being represented.
  string version = 3;
  // Common metadata that all resources share.
  holistik.common.header.v1.Metadata metadata = 4;
  // spec is the specification for the certificate authority.
  CertAuthoritySpec spec = 5;
}

message CertAuthoritySpec {
  // type identifies the type of certificate authority (eg. identity, attestation, etc.)
  string type = 1;

  // tenant identifies the tenant this authority serves
  string tenant = 2;

  // keyset is the CA key set used to sign any new certificates.
  holistik.common.types.v1.CAKeySet keyset = 3;
}
